Repository wecode-bootcamp-korea/baemin_store-frontend, pull requests merged in 2021-01, with the labels that each got.

#2 [16기 김태형] 배민문방구 Footer 구현 완료 + 1.12(리뷰반영)
  public/Images/logo-footer.png
  public/Images/logo-nav.png
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/FooterData.js
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Routes.js
  src/Styles/reset.scss
  src/index.js
Labels: Status: Accepted

#1 [16기 김태형] 배민문방구 Navbar UI 완료 + 1.12(리뷰반영) + 1.13(기능구현) + 1.14(리뷰반영)
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Components/Navbar/NavbarData.js
  src/Routes.js
Labels: Status: 리뷰 요청

#4 [16기 김병진] 배민문방구 Item 컴포넌트 구현 완료 1/14(리뷰 반영) 1/15(리뷰 반영)
  public/index.html
  src/Components/Item/Item.js
  src/Components/Item/Item.scss
  src/Pages/Cart/Components/Cartlist/Cartlist.js
  src/Pages/Cart/Components/Cartlist/Cartlist.scss
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Routes.js
  src/index.js
Labels: Status: 리뷰 요청

#8 [16기 김태형] 배민문방구 회원가입 페이지 및 기능 구현완료(서버연동) + 리뷰반영(1.17)
  public/Images/register-check.png
  src/Components/Footer/Footer.js
  src/Components/Navbar/Navbar.js
  src/Data/Config.js
  src/Pages/Main/Main.js
  src/Pages/Main/MainData.js
  src/Pages/Register/Complete/Complete.js
  src/Pages/Register/Complete/Complete.scss
  src/Pages/Register/Components/JoinStage/JoinStage.js
  src/Pages/Register/Components/JoinStage/JoinStage.scss
  src/Pages/Register/Components/SelectBirth/SelectBirth.js
  src/Pages/Register/Components/SelectBirth/SelectBirth.scss
  src/Pages/Register/EnterJoin/EnterJoin.js
  src/Pages/Register/EnterJoin/EnterJoin.scss
  src/Pages/Register/ExitJoin/ExitJoin.js
  src/Pages/Register/ExitJoin/ExitJoin.scss
  src/Pages/Register/ExitJoin/register_complete.png
  src/Pages/Register/Join/Join.js
  src/Pages/Register/Join/Join.scss
  src/Pages/Register/Join/register_join.png
  src/Routes.js
Labels: Status: 리뷰 요청

#6 [16기 김동하] 배민문방구 Login 페이지 및 기능 구현완료 + 1.18(컨플릭트 해결)
  .gitignore
  public/Images/icon_caution.png
  public/index.html
  src/Data/Config.js
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Login/Login.js
  src/Pages/Login/Login.scss
  src/Pages/Main/Main.scss
  src/Routes.js
  src/Styles/common.scss
  src/Styles/reset.scss
  src/index.js
Labels: Status: 리뷰 요청

#3 [16기 김태형] 배민문방구 Main 페이지 UI 구현중
  public/Images/default2.jpg
  public/Images/recommend1.jpeg
  public/Images/recommend1.jpg
  public/Images/recommend2.jpeg
  public/Images/slider1.jpeg
  public/Images/slider1.png
  public/Images/slider2.jpg
  public/Images/slider3.png
  src/Components/Footer/Footer.scss
  src/Components/Item/Item.scss
  src/Components/Navbar/Components/SearchBar/SearchBar.js
  src/Components/Navbar/Components/SearchBar/SearchBar.scss
  src/Components/Navbar/NavbarData.js
  src/Data/Data.js
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Pages/Main/Components/Carousel/Carousel.js
  src/Pages/Main/Components/Carousel/Carousel.scss
  src/Pages/Main/Components/Recommend/Recommend.js
  src/Pages/Main/Components/Recommend/Recommend.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Routes.js
Labels: Status: 수정 요청

#9 [16기 김태형] 배민문방구 Navbar 검색 모달창 추가구현 Merge 요청
  public/Images/default22.jpg
  src/Components/Navbar/Components/SearchModal/SearchModal.js
  src/Components/Navbar/Components/SearchModal/SearchModal.scss
  src/Components/Navbar/Navbar.js
  src/Components/Navbar/Navbar.scss
  src/Data/Config.js
  src/index.scss
Labels: Status: 수정 요청

#7 [16기 김병진] 배민문방구 Detail 페이지 UI 구현 완료 1/21 (conflict 해결 완료)
  public/Images/detail.png
  public/Images/listItem.png
  src/Pages/Category/Category.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailExact.js
  src/Pages/Detail/DetailExact.scss
  src/Pages/Detail/DetailInfo.js
  src/Pages/Detail/DetailInfo.scss
  src/Pages/Detail/DetailTable.js
  src/Pages/Detail/DetailTable.scss
  src/Routes.js
  src/Styles/common.scss
Labels: Status: 리뷰 요청

#10 [16기 김병진] 배민문방구 Category/Item 페이지 데이터 매핑 완료 1/19(리뷰반영 완료) 1/22(리뷰반영 conflict 해결)
  public/data/product.json
  src/Components/Item/Item.js
  src/Components/Item/Item.scss
  src/Components/Navbar/Navbar.js
  src/Data/Data.js
  src/Pages/Category/Buttons.js
  src/Pages/Category/Category.js
  src/Pages/Category/Category.scss
  src/Pages/Detail/Detail.js
  src/Pages/Detail/Detail.scss
  src/Pages/Detail/DetailTable.js
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: Accepted
